# Generated by Django 3.2.6 on 2021-09-02 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cashback', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apimaistodos',
            old_name='cashback',
            new_name='cashback_mt',
        ),
        migrations.RenameField(
            model_name='buy',
            old_name='cash',
            new_name='cashback',
        ),
    ]
